# This file was generated by GoReleaser. DO NOT EDIT.
class Dkl < Formula
  desc "dkl is the text-mode interface for docker and kubectl command."
  homepage "https://budougumi0617.github.io/"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/budougumi0617/dkl/releases/download/v0.0.1/dkl_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "9d59d8e4540aa11b22bdbde31237944b4c8abc3c71569ba45745eaa840e9d50e"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/budougumi0617/dkl/releases/download/v0.0.1/dkl_0.0.1_Linux_x86_64.tar.gz"
      sha256 "aa5a5fe94bb41585184f1ed628cbc5a62ca2bbedeaa610e51f899190f803a5b5"
    end
  end

  def install
    bin.install "dkl"
  end

  test do
    system "#{bin}/dkl --version"
  end
end
