# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gigi < Formula
  desc "Check pull request size."
  homepage "https://github.com/budougumi0617/gigi"
  version "0.0.8"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/budougumi0617/gigi/releases/download/v0.0.8/gigi_0.0.8_Darwin_x86_64.tar.gz"
    sha256 "123cec2b39544146a51827fe9651cff3fb89f9b76eec969c957e32d001298236"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/budougumi0617/gigi/releases/download/v0.0.8/gigi_0.0.8_Darwin_arm64.tar.gz"
    sha256 "6a5bdf9b95b348ea32037f2f77df35aa8b97587ad14e8ba428b505993b1addb5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/budougumi0617/gigi/releases/download/v0.0.8/gigi_0.0.8_Linux_x86_64.tar.gz"
    sha256 "c5531ab7f0c302b67b8f3d8b3e0f435f4291f6fcca53503aaad5f710e2561593"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/budougumi0617/gigi/releases/download/v0.0.8/gigi_0.0.8_Linux_arm64.tar.gz"
    sha256 "1a59772500e5fc7c8c14ee23b72d051f3f2a68cef6c4a620330e7e3d6a36e1df"
  end

  def install
    bin.install "gigi"
  end

  test do
    system "#{bin}/gigi -h"
  end
end
