# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gigi < Formula
  desc "Check pull request size."
  homepage "https://github.com/budougumi0617/gigi"
  version "0.0.4"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/budougumi0617/gigi/releases/download/v0.0.4/gigi_0.0.4_Darwin_x86_64.tar.gz"
    sha256 "34540a2ee1d26163bda040c383ad3317fea027067841c73499ab7b17ce395a57"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/budougumi0617/gigi/releases/download/v0.0.4/gigi_0.0.4_Darwin_arm64.tar.gz"
    sha256 "20237cc0a5db404e0602ae673015b606cf9e6abbd9012e3962a607e897edb841"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/budougumi0617/gigi/releases/download/v0.0.4/gigi_0.0.4_Linux_x86_64.tar.gz"
    sha256 "b5bb8250bf228fc5443c48b02ec56a052c2363c337ae82e625ac300645e9f167"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/budougumi0617/gigi/releases/download/v0.0.4/gigi_0.0.4_Linux_arm64.tar.gz"
    sha256 "7e86242e5b014e13b00fc0fd2867b96c5f225f67d6048521ecb86505a4cfdd3f"
  end

  def install
    bin.install "gigi"
  end

  test do
    system "#{bin}/gigi -h"
  end
end
