# This file was generated by GoReleaser. DO NOT EDIT.
class Leetgode < Formula
  desc "LeetCode CLI for Gophers."
  homepage "https://budougumi0617.github.io/"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/budougumi0617/leetgode/releases/download/v0.0.1/leetgode_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "8f430d07059b5ba7007b5dc203b2381ddbf7f55054d9bf61787568d51f927a08"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/budougumi0617/leetgode/releases/download/v0.0.1/leetgode_0.0.1_Linux_x86_64.tar.gz"
      sha256 "f81712c453f6f7bd4e129246c06848e34fb577778610ca6019eebb326bcffa6b"
    end
  end

  def install
    bin.install "leetgode"
  end

  test do
    system "#{bin}/leetgode help"
  end
end
