# This file was generated by GoReleaser. DO NOT EDIT.
class Lgen < Formula
  desc "lgen generates boilerplates for layered architecture"
  homepage "https://budougumi0617.github.io/"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/budougumi0617/lgen/releases/download/v0.0.2/lgen_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "3e09b933e7589fddcdda0439889634704dd533c7391f0a55768dea671bb1281d"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/budougumi0617/lgen/releases/download/v0.0.2/lgen_0.0.2_Linux_x86_64.tar.gz"
      sha256 "ee7078b4bb7373b385d63bc44cf8539f5fb413d0cb7ebd95f66ca8d60b3401c8"
    end
  end

  def install
    bin.install "lgen"
  end

  test do
    system "#{bin}/lgen --version"
  end
end
