# This file was generated by GoReleaser. DO NOT EDIT.
class Lgen < Formula
  desc "lgen generates boilerplates for layered architecture"
  homepage "https://budougumi0617.github.io/"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/budougumi0617/lgen/releases/download/v0.0.3/lgen_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "2d51f1e53ac297e5136e7d4e11f42a3216258cd88786687b37562b85f64b7265"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/budougumi0617/lgen/releases/download/v0.0.3/lgen_0.0.3_Linux_x86_64.tar.gz"
      sha256 "31b1bd797332fdc2b7ac474669f9071261d079301fbf6ff1e22efff4efa14191"
    end
  end

  def install
    bin.install "lgen"
  end

  test do
    system "#{bin}/lgen --version"
  end
end
