# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nrseg < Formula
  desc "Insert function segments into any function/method for Newrelic APM."
  homepage "https://github.com/budougumi0617/nrseg"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/budougumi0617/nrseg/releases/download/v0.0.5/nrseg_0.0.5_Darwin_x86_64.tar.gz"
    sha256 "5d8428243fa67bc930ee2adc602eaf9c0d70eba702c67a8e259dbf56813b3a81"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/budougumi0617/nrseg/releases/download/v0.0.5/nrseg_0.0.5_Linux_x86_64.tar.gz"
    sha256 "a72745afc3b78eb4dddd61e0c8a58478b47edbac3eb58e369708017b958e65b3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/budougumi0617/nrseg/releases/download/v0.0.5/nrseg_0.0.5_Linux_arm64.tar.gz"
    sha256 "64015e66cb08a89ac6193be46890b0108c7251d4e799d544bd59d811d4f8c7aa"
  end

  def install
    bin.install "nrseg"
  end

  test do
    system "#{bin}/nrseg -h"
  end
end
