# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nrseg < Formula
  desc "Insert function segments into any function/method for Newrelic APM."
  homepage "https://github.com/budougumi0617/nrseg"
  version "0.0.3"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/budougumi0617/nrseg/releases/download/v0.0.3/nrseg_0.0.3_Darwin_x86_64.tar.gz"
    sha256 "78fe412097dbbaf2087540e468064bdbb2eb59ea8bdf415971b56e450abebee9"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/budougumi0617/nrseg/releases/download/v0.0.3/nrseg_0.0.3_Linux_x86_64.tar.gz"
    sha256 "1bc2c3995a0e0510b925d51d72d7e745eeff985a9a27779b87cba4620436617f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/budougumi0617/nrseg/releases/download/v0.0.3/nrseg_0.0.3_Linux_arm64.tar.gz"
    sha256 "86d8498bf5d8161ea7b7c5169bb6a562868f2055c863b6caba29cee1a4c61569"
  end

  def install
    bin.install "nrseg"
  end

  test do
    system "#{bin}/nrseg -h"
  end
end
